org.gradle.jvmargs=-Xmx1G

minecraft_version=26.2
parchment_release=2024.11.17
fabric_version=0.19.3
neoforge_version=21.1.119

# Fabric API
fabric_api_version=0.153.0+26.2
jsonem_version=0.3+1.21
controlify_version=3.0.2+26.2
modmenu_version=19.0.0-alpha.1
yacl_version=3.9.5+26.2-fabric

mod_version = 0.5.0-unofficial.26
momentum_version = 0.1.11-unofficial.4
maven_group = io.github.foundationgames
archives_base_name = automobility
